function [schema] = loadGameInfoSchema()
    schema = struct( ...
                    'window', struct('position', zeros(1, 4)), ...
                    'buttons', struct('start', struct('position', zeros(1, 4)), 'stop', struct('position', zeros(1, 4))), ...
                    'pointers', struct('position', zeros(1, 2), 'target', zeros(1, 2)), ...
                    'screen', zeros(1, 2));
end
